version: '3'
services:
  spotify-app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    network_mode: host

  spotify-bot:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "bot.js"]
    network_mode: host