version: '3'
services:
  spotify-app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["nodemon", "index.js"]
    network_mode: host